/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "v5.0.25-52-g3ed4aed82"
#endif /* AVUTIL_FFVERSION_H */
