// auto generated by configure
#ifndef SRS_AUTO_HEADER_HPP
#define SRS_AUTO_HEADER_HPP

#define SRS_PACKAGER ""
#define SRS_BUILD_TS "1654863225"
#define SRS_BUILD_DATE "2022-06-10 20:13:45"
#define SRS_UNAME "Linux ubuntu 5.10.65-tegra #1 SMP PREEMPT Mon May 16 20:58:07 PDT 2022 aarch64 aarch64 aarch64 GNU/Linux"
#define SRS_USER_CONFIGURE "--x86-x64 --full"
#define SRS_CONFIGURE "--prefix=/usr/local/srs --config=conf/srs.conf --hls=on --hds=off --dvr=on --ssl=on --https=on --ssl-1-0=off --ssl-local=off --sys-ssl=off --transcode=on --ingest=on --stat=on --http-callback=on --http-server=on --stream-caster=on --http-api=on --utest=off --cherrypy=off --srt=off --rtc=on --simulator=off --cxx11=on --cxx14=off --ffmpeg-fit=on --nasm=on --srtp-nasm=on --clean=on --gperf=off --gmc=off --gmd=off --gmp=off --gcp=off --gprof=off --static=off --shared-st=off --shared-srt=off --shared-ffmpeg=off --log-verbose=off --log-info=off --log-trace=on --gcov=off --debug=off --debug-stats=off --cross-build=off --cc=gcc --cxx=g++ --ar=ar --ld=ld --randlib=randlib"

#undef SRS_HDS
#define SRS_HDS_BOOL false
#undef SRS_SRT
#define SRS_SRT_BOOL false
#define SRS_CXX11
#define SRS_CXX11_BOOL true
#undef SRS_CXX14
#define SRS_CXX14_BOOL false
#define SRS_RTC
#define SRS_RTC_BOOL true
#define SRS_FFMPEG_FIT
#define SRS_FFMPEG_FIT_BOOL true
#undef SRS_SIMULATOR
#define SRS_SIMULATOR_BOOL false
#define SRS_HTTPS
#define SRS_HTTPS_BOOL true
#undef SRS_UTEST
#define SRS_UTEST_BOOL false
#define SRS_FFMPEG_STUB
#define SRS_FFMPEG_STUB_BOOL true
#undef SRS_GPERF
#define SRS_GPERF_BOOL false
#undef SRS_GPERF_MC
#define SRS_GPERF_MC_BOOL false
#undef SRS_GPERF_MD
#define SRS_GPERF_MD_BOOL false
#undef SRS_GPERF_MP
#define SRS_GPERF_MP_BOOL false
#undef SRS_GPERF_CP
#define SRS_GPERF_CP_BOOL false
#undef SRS_VERBOSE
#define SRS_VERBOSE_BOOL false
#undef SRS_INFO
#define SRS_INFO_BOOL false
#define SRS_TRACE
#define SRS_TRACE_BOOL true
#undef SRS_CROSSBUILD
#define SRS_CROSSBUILD_BOOL false
#undef SRS_OSX
#define SRS_OSX_BOOL false
#undef SRS_DEBUG
#define SRS_DEBUG_BOOL false
#undef SRS_DEBUG_STATS
#define SRS_DEBUG_STATS_BOOL false

#define SRS_PREFIX "/usr/local/srs"
#define SRS_DEFAULT_CONFIG "conf/srs.conf"

#define RTMP_SIG_SRS_AUTHORS "\
Winlin<winlin@vip.126.com> \
ZhaoWenjie<zhaowenjie@tal.com> \
ShiWei<shiwei05@kuaishou.com> \
XiaoZhihong<hondaxiao@tencent.com> \
WuPengqiang<pengqiang.wpq@alibaba-inc.com> \
XiaLixin<xialixin@kanzhun.com> \
LiPeng<mozhan.lp@alibaba-inc.com> \
ChenGuanghua<jinxue.cgh@alibaba-inc.com> \
ChenHaibo<nmgchenhaibo@foxmail.com> \
Johzzy<hellojinqiang@gmail.com> \
Zhouxiaojun2008<279686030@qq.com> \
Pengfei.ma<pengfei.ma.chn@outlook.com> \
ZhangJunqin<zhangjunqin@jd.com> \
"

#endif

